routes/web.php
<?php
//Route::get('email',function (){
//    return new App\Mail\LoginCredentials(App\User::find(5), '12345');
//});
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('posts/{post}/comments', 'Admin\CommentController@store')->name('posts.comments.store');
Route::resource('admin/comments', 'CommentController',['except'=>['store'], 'as' => 'posts']);




Route::get('set_language/{lang}','Controller@setLangugae')->name('set_language');
Route::get('/', 'PagesController@home')->name('pages.home');
Route::get('about', 'PagesController@about')->name('pages.about');
Route::get('archive', 'PagesController@archive')->name('pages.archive');
Route::get('contact', 'PagesController@contact')->name('pages.contact');

Route::get('posts', 'PagesController@home');
Route::get('blog/{post}', 'PostsController@show')->name('posts.show');
Route::get('categories/{category}', 'CategoriesController@show')->name('categories.show');
Route::get('tags/{tag}', 'TagsController@show')->name('tags.show');

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => 'auth'
], function() {
    Route::get('/', 'AdminController@index')->name('dashboard');

    Route::resource('posts', 'PostsController', ['except' => ['show', 'create'], 'as' => 'admin']);

    Route::resource('users', 'UsersController', ['as' => 'admin']);

    Route::resource('roles', 'RolesController', ['as' => 'admin']);

    Route::middleware('role:Admin')
        ->put('users/{user}/roles', 'UsersRolesController@update')
        ->name('admin.users.roles.update');
    Route::middleware('role:Admin')
        ->put('users/{user}/permissions', 'UsersPermissionsController@update')
        ->name('admin.users.permissions.update');

    Route::post('posts/{post}/photos', 'PhotosController@store')->name('admin.posts.photos.store');
    Route::delete('photos/{photo}', 'PhotosController@destroy')->name('admin.photos.destroy');
});



Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Traits\HasRoles; //Añadirlo

class User extends Authenticatable
{
    use Notifiable, HasRoles, SoftDeletes;


    public function scopeAllowed($query)
    {
        if(auth()->user()->can('view', $this)) { //Si el usuario puede ver los post...
            return $query;
        }else {
            return $query->where('id', auth()->id());
        }
    }
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Events\UserWasCreated;
use App\Http\Requests\UpdateUserRequest;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::allowed()->get();

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User;
        $this->authorize('create',$user);
        $roles = Role::with('permissions')->get();
        $permissions = Permission::pluck('name', 'id');
        return view('admin.users.create', compact('user', 'roles', 'permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create',new User());
        $data = $this->validate($request, [
           'name' => 'required | string | max: 200',
           'email' => 'required | email | string | max: 255 | unique:users'
        ]);

        $data['password'] = Str::random(8); //Generamos una cadena aleatoria definiendo el numero de caracteres

        $user = User::create($data);

        $user->assignRole($request->roles);

        $user->givePermissionTo($request->permissions);

        //Pendiente el envio de correo por Spam
        //NO podemos pasarle $user->password porque estará encriptada
        UserWasCreated::dispatch($user,$data['password']);

        return redirect()->route('admin.users.index')->with('flash', 'Usuario creado correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $this->authorize('view',$user);
        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->authorize('update',$user);
        $roles = Role::with('permissions')->get();
        $permissions = Permission::pluck('name', 'id');
        return view('admin.users.edit', compact('user', 'roles', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, User $user)
    {
        $this->authorize('update',$user);
        $user->update($request->validated());

        return back()->withFlash('Usuario actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->authorize('delete',$user);
        $user->delete();
        return redirect()->route('admin.users.index')->withFlash('El usuario'.$user->name.'ha sido eliminado');
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.layout')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header with-border">
                    <h3 class="card-title">Datos personales</h3>
                </div>
                <div class="card-body">

                    @include('admin.partials.messages')

                    <form action="{{ route('admin.users.store') }}" method="post">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="name">Nombre:</label>
                                    <input type="text" name="name" value="{{ old('name') }}"
                                           class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="email">Email:</label>
                                    <input type="email" name="email" value="{{ old('email') }}"
                                           class="form-control">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Roles</label>
                                @include('admin.roles.checkboxes')
                                <label>Permisos</label>
                                @include('admin.permissions.checkboxes', ['model' => $user])
                            </div>
                        </div>
                        <div class="row">
                            <button type="submit" class="btn btn-primary btn-block">
                                Crear usuario
                            </button>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <span class="form-text">
                        La contraseña será generada automáticamente y enviada al nuevo usuario por email
                    </span>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.layout')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="card card-primary">
                <div class="card-header with-border">
                    <h3 class="card-title">Datos Personales</h3>
                </div>
                <div class="card-body">
                    @if($errors->any())
                        <ul class="list-group">
                            @foreach($errors->all() as $error)
                                <li class="list-group-item list-group-item-danger">
                                    {{ $error }}
                                </li>
                            @endforeach
                        </ul>
                    @endif
                    <form action="{{ route('admin.users.update', $user) }}" method="post">
                        @csrf
                        @method('put')
                        <div class="form-group">
                            <label for="name">Nombre: </label>
                            <input type="text" name="name" value="{{ old('name', $user->name) }}"
                                   class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" name="email" value="{{ old('email', $user->email) }}"
                                   class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="password">Contraseña: </label>
                            <input type="password" name="password" class="form-control"
                                   placeholder="Contraseña">
                            <span class="form-text">Dejar en blanco si no desea cambiarla</span>
                        </div>
                        <div class="form-group">
                            <label for="password_confirmation">Repite contraseña: </label>
                            <input type="password" name="password_confirmation" class="form-control"
                                   placeholder="Repite la contraseña">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Actualizar usuario</button>
                        <a href="{{ route('admin.users.index') }}" class="btn btn-default btn-block">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card card-primary">
                <div class="card-header with-border">
                    <h3 class="card-title">Roles</h3>
                </div>
                <div class="card-body">
                    @role('Admin')
                    <form action="{{ route('admin.users.roles.update', $user) }}" method="post">
                        @csrf @method('put')
                        @include('admin.roles.checkboxes')
                        <button class="btn btn-primary btn-block">Actualizar Roles</button>
                    </form>
                    @else
                        <ul class="list-group">
                            @forelse($user->roles as $role)
                                <li class="list-group-item">{{ $role->name }}</li>
                            @empty
                                <li class="list-group-item">No tienes roles asignados</li>
                            @endforelse
                        </ul>
                        @endrole
                </div>
            </div>
            <div class="card card-primary">
                <div class="card-header with-border">
                    <h3 class="card-title">Permisos</h3>
                </div>
                <div class="card-body">
                    <form action="{{ route('admin.users.permissions.update', $user) }}" method="post">
                        @csrf @method('put')
                        @include('admin.permissions.checkboxes', ['model' => $user])
                        <button class="btn btn-primary btn-block">Actualizar Permisos</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.layout')

@section('header')
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">Usuarios</h1>
            <small>Listado completo de Usuarios</small>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                <li class="breadcrumb-item active">Usuarios</li>
            </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
@endsection
@section('content')
    <div class="card">
        <div class="card-header">
            <div class="card-title">Listado de usuarios</div>
            <a href="{{ route('admin.users.create') }}" class="btn btn-primary float-right">
                <i class="fa fa-plus"></i> Crear Usuario
            </a>
        </div>
        <div class="card-body">
            <table id="users-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Roles</th>
                    <th>Visitas</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->getRoleNames()->implode(',') }}</td>
                        <td>{{ $user->visitas }}</td><!-- El metodo implode() convierte de un array en un string sepadado por comas -->
                        <td>
                            <a href="{{ route('admin.users.show', $user) }}" class="btn btn-xs btn-default"><i class="fa fa-eye"></i></a>
                            <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-xs btn-info"><i class="fa fa-pencil-alt"></i></a>
                            <form action="{{ route('admin.users.destroy', $user) }}" method="POST" class="d-inline">
                                @csrf
                                @method('DELETE')
                                <button href="#" class="btn btn-xs btn-danger" onclick="return confirm('¿Estas seguro que quieres eliminar este usuario?')"><i class="fa fa-times"></i></button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

@push('styles')
    <link rel="stylesheet" href="/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
@endpush

@push('scripts')
    <!-- DataTables -->
    <script src="/adminlte/plugins/datatables/jquery.dataTables.js"></script>
    <script src="/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>

    <script>
        $(function () {
            $('#users-table').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });
        });
    </script>
@endpush

resources/views/admin/users/show.blade.php
@extends('admin.layouts.layout')

@section('header')
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">Perfil del usuario</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">Usuarios</a></li>
                <li class="breadcrumb-item active">Perfil</li>
            </ol>
        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-3">
            <div class="card card-primary card-outline">
                <div class="card-body box-profile">
                    <div class="text-center">
                        <img class="profile-user-img img-fluid img-circle"
                             src="/adminlte/dist/img/user4-128x128.jpg"
                             alt="User profile picture">
                    </div>

                    <h3 class="profile-username text-center">{{ $user->name }}</h3>

                    <p class="text-muted text-center">{{ $user->getRoleNames()->implode(', ') }}</p>

                    <ul class="list-group list-group-unbordered mb-3">
                        <li class="list-group-item">
                            <b>Email</b> <a class="float-right ml-5">{{ $user->email }}</a>
                        </li>
                        <li class="list-group-item">
                            <b>Posts</b> <a class="float-right">{{ $user->posts->count() }}</a>
                        </li>
                        @if($user->roles->count())
                        <li class="list-group-item">
                            <b>Roles</b> <a class="float-right">{{ $user->getRoleNames()->implode(', ') }}</a>
                        </li>
                        @endif
                    </ul>

                    <a href="#" class="btn btn-primary btn-block"><b>Editar</b></a>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-primary">
                <div class="card-header with-border">
                    <h3 class="card-title">Posts</h3>
                </div>
                <div class="card-body">
                    @forelse($user->posts as $post)
                        <a href="{{ route('posts.show', $post) }}" target="_blank">
                            <strong>{{ $post->title }}</strong>
                        </a>
                        <br>
                        <small class="text-muted">Publicado el {{ $post->published_at->format('d/m/Y') }}</small>
                        <p class="text-muted">{{ $post->excerpt }}</p>
                    @unless($loop->last)
                        <hr>
                    @endunless
                    @empty
                         <small class="text-muted">No tiene posts</small>
                    @endforelse
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-secondary">
                <div class="card-header with-border">
                    <h3 class="card-title">Roles</h3>
                </div>
                <div class="card-body">
                    @forelse($user->roles as $role)
                        <strong>{{ $role->name }}</strong>
                        @if($role->permissions->count())
                            <br>
                            <small class="text-muted">Permisos: {{ $role->permissions->pluck('name')->implode(', ') }}</small>
                        @endif
                        @unless($loop->last)
                            <hr>
                        @endunless
                    @empty
                        <small class="text-muted">No tienes roles</small>
                    @endforelse
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-info">
                <div class="card-header with-border">
                    <h3 class="card-title">Permisos extra</h3>
                </div>
                <div class="card-body">
                    @forelse($user->permissions as $permission)
                        <strong>{{ $permission->name }}</strong>
                        @unless($loop->last)
                            <hr>
                        @endunless
                    @empty
                        <small class="text-muted">No tienes permisos adicionales</small>
                    @endforelse
                </div>
            </div>
        </div>
    </div>

@endsection