routes/web.php
<?php
//Route::get('email',function (){
//    return new App\Mail\LoginCredentials(App\User::find(5), '12345');
//});
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('posts/{post}/comments', 'Admin\CommentController@store')->name('posts.comments.store');
Route::resource('admin/comments', 'CommentController',['except'=>['store'], 'as' => 'posts']);




Route::get('set_language/{lang}','Controller@setLangugae')->name('set_language');
Route::get('/', 'PagesController@home')->name('pages.home');
Route::get('about', 'PagesController@about')->name('pages.about');
Route::get('archive', 'PagesController@archive')->name('pages.archive');
Route::get('contact', 'PagesController@contact')->name('pages.contact');

Route::get('posts', 'PagesController@home');
Route::get('blog/{post}', 'PostsController@show')->name('posts.show');
Route::get('categories/{category}', 'CategoriesController@show')->name('categories.show');
Route::get('tags/{tag}', 'TagsController@show')->name('tags.show');

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => 'auth'
], function() {
    Route::get('/', 'AdminController@index')->name('dashboard');

    Route::resource('posts', 'PostsController', ['except' => ['show', 'create'], 'as' => 'admin']);

    Route::resource('users', 'UsersController', ['as' => 'admin']);

    Route::resource('roles', 'RolesController', ['as' => 'admin']);

    Route::middleware('role:Admin')
        ->put('users/{user}/roles', 'UsersRolesController@update')
        ->name('admin.users.roles.update');
    Route::middleware('role:Admin')
        ->put('users/{user}/permissions', 'UsersPermissionsController@update')
        ->name('admin.users.permissions.update');

    Route::post('posts/{post}/photos', 'PhotosController@store')->name('admin.posts.photos.store');
    Route::delete('photos/{photo}', 'PhotosController@destroy')->name('admin.photos.destroy');
});



Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

resources/views/admin/partials/messages.blade.php
@if($errors->any())
    <ul class="list-group">
        @foreach($errors->all() as $error)
            <li class="list-group-item list-group-item-danger">
                {{ $error }}
            </li>
        @endforeach
    </ul>
@endif

resources/views/admin/partials/nav.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="/adminlte/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">{{ config('app.name') }}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="/adminlte/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ auth()->user()->name }} | {{ auth()->user()->roles->first()->name }}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="{{ route('dashboard') }}" class="nav-link {{ setActiveRoute('dashboard') }}">
                        <i class="nav-icon fas fa-th"></i>
                        <p>Inicio</p>
                    </a>
                </li>
                <li class="nav-item has-treeview menu-open">
                    <a href="" class="nav-link {{ setActiveRoute('admin.users*') }}">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Usuarios
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('admin.users.index') }}" class="nav-link {{ setActiveRoute('admin.users.index') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Ver todos los usuarios</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.users.create') }}" class="nav-link {{ setActiveRoute('admin.users.create') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Crear un usuario</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview menu-open">
                    <a href="" class="nav-link {{ setActiveRoute('admin.posts*') }}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Post
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('admin.posts.index') }}" class="nav-link {{ setActiveRoute('admin.posts') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Ver todos los post</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            @if(request()->is('admin/posts/*'))
                                <a href="{{ route('admin.posts.index', '#create') }}" class="nav-link {{ setActiveRoute('admin.posts.index') }}">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Crear un post</p>
                                </a>
                            @else
                                <a href="#" class="nav-link {{ request()->is('admin/posts/create') ? 'active' : '' }}" data-toggle="modal" data-target="#crearPost">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Crear un post</p>
                                </a>
                            @endif
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>